name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cd build && make -j
    - name: Test
      run: cd build/test && ctest
